import { Selectable } from "kysely";

export interface Database {
  people: PersonTable;
  champions: ChampionTable;
}

export interface PersonTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: number;
  player: string;
  fname: string;
  lname: string;
  slug: string;
  schools: string;
  tournaments: number;
}

export interface ChampionTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  year: string;
  tournament: string;
  school: string;
  team: string;
  team_id: string | null;
  tournament_id: number | null;
}

// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.
export type Person = Selectable<PersonTable>;

export type YearChampions = Selectable<ChampionTable>;


